### ISSUE TITLE
Cannot run any commands in version 0.1.36

### ISSUE THREAD

**Issue by eolszewski** [transmute-industries/transmute-cli#6]
Error Received:
```
module.js:529
    throw err;
    ^

Error: Cannot find module 'websocket-driver'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/transmute-cli/node_modules/faye-websocket/lib/faye/websocket.js:8:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by OR13** [comment]
maybe also you need firebase installed globally...

```
npm install -g firebase-tools --engine-strict=false
```

**Comment by eolszewski** [comment]
@OR13 I had to run transmute setup before anything would work.
